package views.screen.bike;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import configs.Path;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import model.BikeModel;
import views.screen.BaseScreenHandler;
import views.screen.home.HomeScreenHandler;
import views.screen.payment.PaymentScreenHandler;

public class BikeScreenHandler  extends BaseScreenHandler implements Initializable{
	
	@FXML
	private Label lbName;
	@FXML
	private Label lbType;
	@FXML
	private Label lbWeight;
	@FXML
	private Label lbLicensePlate;
	@FXML
	private Label lbManuafacturingDate;
	@FXML
	private Label lbCost;
	@FXML
	private Label lbProducer;
	@FXML
	private Label lbBattery;
	@FXML
	private Label lbLoadCycles;
	@FXML
	private Label lbTimeRemaining;
	
	private BikeModel bike;
	
	public BikeScreenHandler(Stage stage, String screenPath, BikeModel bike) throws IOException {
		super(stage, screenPath);
		// TODO Auto-generated constructor stub
		this.bike = bike;
		if(bike.getName() != null) {
			lbName.setText(bike.getName());
		}
		if(bike.getType() != null) {
			lbType.setText(bike.getType());
		}
		if(bike.getWeight() != null) {
			lbWeight.setText(bike.getWeight().toString());
		}
		if(bike.getLicense_plate() != null) {
			lbLicensePlate.setText(bike.getLicense_plate());
		}
		if(bike.getManuafacturing_date() != null) {
			lbManuafacturingDate.setText(bike.getManuafacturing_date().toString());
		}
		if(bike.getCost() != null) {
			lbCost.setText(bike.getCost().toString());
		}
		if(bike.getProducer() != null) {
			lbProducer.setText(bike.getProducer());
		}
		if(bike.getBattery() != null) {
			lbBattery.setText(bike.getBattery().toString());
		}
		if(bike.getLoad_cycles() != null) {
			lbLoadCycles.setText(bike.getLoad_cycles().toString());
		}
		if(bike.getTime_remaining() != null) {
			lbTimeRemaining.setText(bike.getTime_remaining().toString());
		}
		
	}
	
	// Event Listener on Button[#btnRent].onMouseClicked
	@FXML
	public void rentBike(MouseEvent event) throws IOException {
		// TODO Autogenerated
		PaymentScreenHandler paymentScreenHandler = new PaymentScreenHandler(stage, Path.PAYMENT, bike);
		paymentScreenHandler.setScreenTitle("Payment Screen");
		paymentScreenHandler.show();
	}
	// Event Listener on Button[#btnBack].onMouseClicked
	@FXML
	public void backScreen(MouseEvent event) throws IOException {
		// TODO Autogenerated
		HomeScreenHandler homeScreenHandler = new HomeScreenHandler(stage, Path.HOME);
		homeScreenHandler.setScreenTitle("Home Screen");
		homeScreenHandler.show();
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
