package views.screen.home;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Pagination;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
import views.screen.BaseScreenHandler;

public class HomeScreenHandler extends BaseScreenHandler implements Initializable {
	@FXML
	private TextField searchQuery;
	@FXML
	private GridPane dockGrid;
	@FXML
	private Pagination pagination;
	
	public HomeScreenHandler(Stage stage, String screenPath) throws IOException {
		super(stage, screenPath);
		// TODO Auto-generated constructor stub
	}
	
	// Event Listener on Button[#searchButton].onMouseClicked
	@FXML
	public void onSearchButtonClick(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
	}
}

